apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/smoke2
  creationTimestamp: null
  name: smoke2.apps.local.20241001.2035.51544
spec:
  refName: smoke2.apps.local
  releasedAt: "2024-10-01T20:38:10Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: harbor.kirkware.net/kirkware-apps/smoke2@sha256:c5decc0fcb48d2cc97ab6cd01d7391e1a2af9a8503bfb41f76279c040d120d17
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20241001.2035.51544
