apiVersion: spaces.tanzu.vmware.com/v1alpha1
kind: AvailabilityTarget
metadata:
  name: fsi-epc
  description: Availability Target for All EPC Clusters
  namespace: default
  spec:
    affinity:
      clusterAffinity:
        clusterSelectorTerms:
        - matchExpressions:
          - key: epc-env
            operator: In
            values:
            - tse-fsi-aviwcp