apiVersion: spaces.tanzu.vmware.com/v1alpha1
kind: Space
metadata:
  name: kwf-smoke-dev
spec:
  template:
    spec:
      profiles:
      - name: apps.tanzu.vmware.com
      resources:
        limits:
          cpu: "5"
          memory: 10Gi
  availabilityTargets:
  - name: fsi-epc
    replicas: 1
  updateStrategy:
    type: RollingUpdate
---
apiVersion: spaces.tanzu.vmware.com/v1alpha1
kind: SpaceDisruptionBudget
metadata:
  name: kwf-smoke-dev
spec:
  availabilityTargets:
  - name: fsi-epc
    minAvailable: 1