---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  creationTimestamp: null
  name: k8sgateway.tanzu.vmware.com
  namespace: default
spec:
  packageRef:
    refName: k8sgateway.tanzu.vmware.com
    versionSelection:
      constraints: '>0.0.0'
      prereleases: {}
  serviceAccountName: default
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  creationTimestamp: null
  name: observability.tanzu.vmware.com
  namespace: default
spec:
  packageRef:
    refName: observability.tanzu.vmware.com
    versionSelection:
      constraints: '>0.0.0'
      prereleases: {}
  serviceAccountName: default
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  creationTimestamp: null
  name: mtls.tanzu.vmware.com
  namespace: default
spec:
  packageRef:
    refName: mtls.tanzu.vmware.com
    versionSelection:
      constraints: '>0.0.0'
      prereleases: {}
  serviceAccountName: default
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  creationTimestamp: null
  name: tanzu-servicebinding.tanzu.vmware.com
  namespace: default
spec:
  packageRef:
    refName: tanzu-servicebinding.tanzu.vmware.com
    versionSelection:
      constraints: '>0.0.0'
      prereleases: {}
  serviceAccountName: default
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  creationTimestamp: null
  name: cert-manager.tanzu.vmware.com
  namespace: default
spec:
  packageRef:
    refName: cert-manager.tanzu.vmware.com
    versionSelection:
      constraints: '>0.0.0'
      prereleases: {}
  serviceAccountName: default
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  creationTimestamp: null
  name: container-apps.tanzu.vmware.com
  namespace: default
spec:
  packageRef:
    refName: container-apps.tanzu.vmware.com
    versionSelection:
      constraints: '>0.0.0'
      prereleases: {}
  serviceAccountName: default
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  creationTimestamp: null
  name: servicebinding.tanzu.vmware.com
  namespace: default
spec:
  packageRef:
    refName: servicebinding.tanzu.vmware.com
    versionSelection:
      constraints: '>0.0.0'
      prereleases: {}
  serviceAccountName: default
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  creationTimestamp: null
  name: bitnami.services.tanzu.vmware.com
  namespace: default
spec:
  packageRef:
    refName: bitnami.services.tanzu.vmware.com
    versionSelection:
      constraints: '>0.0.0'
      prereleases: {}
  serviceAccountName: default
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  creationTimestamp: null
  name: spring-cloud-gateway.tanzu.vmware.com
  namespace: default
spec:
  packageRef:
    refName: spring-cloud-gateway.tanzu.vmware.com
    versionSelection:
      constraints: '>0.0.0'
      prereleases: {}
  serviceAccountName: default
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  creationTimestamp: null
  name: crossplane.tanzu.vmware.com
  namespace: default
spec:
  packageRef:
    refName: crossplane.tanzu.vmware.com
    versionSelection:
      constraints: '>0.0.0'
      prereleases: {}
  serviceAccountName: default
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  creationTimestamp: null
  name: tcs.tanzu.vmware.com
  namespace: default
spec:
  packageRef:
    refName: tcs.tanzu.vmware.com
    versionSelection:
      constraints: '>0.0.0'
      prereleases: {}
  serviceAccountName: default
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  creationTimestamp: null
  name: fluxcd-source-controller.tanzu.vmware.com
  namespace: default
spec:
  packageRef:
    refName: fluxcd-source-controller.tanzu.vmware.com
    versionSelection:
      constraints: '>0.0.0'
      prereleases: {}
  serviceAccountName: default
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  creationTimestamp: null
  name: fluxcd-helm-controller.tanzu.vmware.com
  namespace: default
spec:
  packageRef:
    refName: fluxcd-helm-controller.tanzu.vmware.com
    versionSelection:
      constraints: '>0.0.0'
      prereleases: {}
  serviceAccountName: default
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  creationTimestamp: null
  name: egress.tanzu.vmware.com
  namespace: default
spec:
  packageRef:
    refName: egress.tanzu.vmware.com
    versionSelection:
      constraints: '>0.0.0'
      prereleases: {}
  serviceAccountName: default
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
