trigger:
- kirkware
pool:
  vmImage: ubuntu-latest
variables:
- name: Project
  value: briank-gitops
  readonly: false
- name: ContainerRegistry
  value: harbor.kirkware.net/kirkware-apps/{name}
- name: ServiceConnection
  value: tpk8s-registry
- name: BuildPlanSource
  value: simple.tanzu.vmware.com
  readonly: false
- name: GitopsRepoURL
  value: https://github.com/bkirkware/tpk8s-gitops
  readonly: false
steps:
- checkout: self
  persistCredentials: true
- task: Docker@2
  displayName: Login to Container Registry
  inputs:
    command: login
    containerRegistry: $(ServiceConnection)
- task: CmdLine@2
  displayName: Login to Platform
  inputs:
    script: |
      echo export TANZU_CLI_CEIP_OPT_IN_PROMPT_ANSWER=no
      export TANZU_CLI_CEIP_OPT_IN_PROMPT_ANSWER=no
      echo wget https://github.com/vmware-tanzu/tanzu-cli/releases/download/v1.3.0/tanzu-cli-linux-amd64.tar.gz -O /tmp/tanzu.tar.gz
      wget https://github.com/vmware-tanzu/tanzu-cli/releases/download/v1.3.0/tanzu-cli-linux-amd64.tar.gz -O /tmp/tanzu.tar.gz
      echo tar -xvf /tmp/tanzu.tar.gz -C /tmp
      tar -xvf /tmp/tanzu.tar.gz -C /tmp
      echo install /tmp/v1.3.0/tanzu-cli-linux_amd64 /usr/local/bin/tanzu
      install /tmp/v1.3.0/tanzu-cli-linux_amd64 /usr/local/bin/tanzu
      echo tanzu config eula accept
      tanzu config eula accept
      echo tanzu plugin install --group vmware-tanzu/app-developer
      tanzu plugin install --group vmware-tanzu/app-developer

      echo tanzu login
      tanzu login
  env:
    TANZU_API_TOKEN: $(TanzuApiToken)
- task: CmdLine@2
  displayName: Deploy Application
  inputs:
    script: |
      echo git clone $GITOPSREPOURL
      git clone $GITOPSREPOURL
      echo cd tpk8s-gitops/$PROJECT
      cd tpk8s-gitops/$PROJECT
      echo tanzu build config --build-plan-source-type=ucp --containerapp-registry $CONTAINERREGISTRY --build-plan-source $BUILDPLANSOURCE
      tanzu build config --build-plan-source-type=ucp --containerapp-registry $CONTAINERREGISTRY --build-plan-source $BUILDPLANSOURCE

      echo tanzu project use $PROJECT
      tanzu project use $PROJECT

      echo tanzu deploy --diff --nested-contexts --yes
      tanzu deploy --diff --nested-contexts --yes
