apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/metal
  creationTimestamp: null
  name: metal.apps.local.20240815.2027.19803
spec:
  refName: metal.apps.local
  releasedAt: "2024-08-15T20:29:17Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: harbor.kirkware.net/kirkware-apps/metal@sha256:45f6852d60cb1043041ab8e321b76262c2193fc3a10712ff3dd9b937066cba8c
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240815.2027.19803
