apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/metal
  creationTimestamp: null
  name: metal.apps.local.20240815.2110.6193
spec:
  refName: metal.apps.local
  releasedAt: "2024-08-15T21:11:59Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: harbor.kirkware.net/kirkware-apps/metal@sha256:b0761de41e6181bd28b471c20fcf00f575c5d7e30b179fb7b8e84ca6acf0b46f
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240815.2110.6193
