apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/metal
  creationTimestamp: null
  name: metal.apps.local.20240815.1922.2926
spec:
  refName: metal.apps.local
  releasedAt: "2024-08-15T19:23:55Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: harbor.kirkware.net/kirkware-apps/metal@sha256:d3eb34ac648a7ea434ec3700871e2d1b3514b3b16b02d86c2054a4370d268250
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240815.1922.2926
