apiVersion: services.tanzu.vmware.com/v1
kind: PreProvisionedService
metadata:
  name: genai
spec:
  bindingConnectors:
  - name: main
    description: Gen AI credentials
    type: openai
    secretRef:
      name: genai-creds
