apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins
spec:
  chart:
    spec:
      chart: jenkins
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 13.4.0
  install:
    createNamespace: true
  interval: 10m
  timeout: 5m
  serviceAccountName: fluxcd-helmrelease-installer
  valuesFrom:
  - kind: Secret
    name: jenkins-config
    valuesKey: inline-configurations