apiVersion: v1
kind: Secret
metadata:
  name: docker-creds
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsicGFzc3dvcmQiOiJkY2tyX3BhdF9oTFEyeG5MNHBSVWFEcjE5ajk3amxxRS1WUDAiLCJ1c2VybmFtZSI6ImJraXJrd2FyZSJ9fX0=
