apiVersion: spaces.tanzu.vmware.com/v1alpha1
kind: AvailabilityTarget
metadata:
  name: kw-aws-dev
  description: Availability Target for - aws - dev
  namespace: default
spec:
  affinity:
    clusterAffinity:
      clusterSelectorTerms:
      - matchExpressions:
        - key: kw-aws
          operator: Exists
        - key: kw-dev
          operator: Exists
