apiVersion: spaces.tanzu.vmware.com/v1alpha1
kind: Profile
metadata:
  name: kirkware-network-profile
spec:
  description: kirkware networking setup
  requiredCapabilities:
    - name: egress.tanzu.vmware.com
  #  - name: multicloud-cert-manager.tanzu.vmware.com
  #  - name: multicloud-ingress.tanzu.vmware.com
  traits:
  # - name: egress.tanzu.vmware.com
  #   alias: egress
  - name: multicloud-cert-manager.tanzu.vmware.com
    alias: multicloud-cert-manager
  - name: multicloud-ingress.tanzu.vmware.com
    alias: multicloud-ingress.tanzu.vmware.com
    values:
      inline:
        multicloud-ingress.tanzu.vmware.com:
          name: default-gateway
          domain: kirkware.net
          gslb:
            authentication:
              credentialRef: a4b1028b3c191e497ad000c9ba5e3fce
            dns:
              zoneId: Z0523123KKDB67R7F352
          listenerTemplates:
          - namePrefix: https-
            port: 443
            protocol: HTTPS
            tls:
              secretRef: prod-certs
          - namePrefix: http-
            port: 80
            protocol: HTTP
            tls:
              secretRef: ""
