apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/spring-petclinic-aa-demo
  creationTimestamp: null
  name: spring-petclinic-aa-demo.apps.local.20241010.1435.34206
spec:
  refName: spring-petclinic-aa-demo.apps.local
  releasedAt: "2024-10-10T14:36:27Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: harbor.kirkware.net/kirkware-apps/spring-petclinic-aa-demo@sha256:79dd5a9bd65eac682a9dce33df0bf5175b7b40c599dacc9d22db3c42c824252d
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20241010.1435.34206
